// ─── Edit these lists to match your sweepstakes ─────────────────────────────
// All three arrays must be the same length (up to 24 entries).

export const COMPANY_TEAMS: string[] = [
  "Absence",
  "Academy",
  "Analytics",
  "Andromeda",
  "App Platform",
  "Architecture",
  "Aries",
  "Basilisk",
  "Cloud",
  "Data",
  "Gaia",
  "Helios",
  "Jupiter",
  "Leo",
  "Luna",
  "Nexus",
  "Pixis",
  "Quasar & Voyager",
  "Scheduling",
  "Sirius",
  "Team Principal",
  "Time",
  "Titan & Aurora (AI)",
  "UX",
];

// Stronger / higher FIFA-ranked FIFA WC 2026 nations
export const MAJOR_TEAMS: string[] = [
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Brazil",
  "Colombia",
  "Croatia",
  "Ecuador",
  "England",
  "France",
  "Germany",
  "Iran",
  "Japan",
  "Mexico",
  "Morocco",
  "Netherlands",
  "Portugal",
  "Senegal",
  "South Korea",
  "Spain",
  "Switzerland",
  "Türkiye",
  "Uruguay",
  "USA",
];

// Smaller / lower FIFA-ranked FIFA WC 2026 nations
export const MINOR_TEAMS: string[] = [
  "Algeria",
  "Bosnia and Herzegovina",
  "Canada",
  "Cape Verde",
  "Curacao",
  "Czechia",
  "DR Congo",
  "Egypt",
  "Ghana",
  "Haiti",
  "Iraq",
  "Ivory Coast",
  "Jordan",
  "New Zealand",
  "Norway",
  "Panama",
  "Paraguay",
  "Qatar",
  "Saudi Arabia",
  "Scotland",
  "South Africa",
  "Sweden",
  "Tunisia",
  "Uzbekistan",
];

// ─── Flag image codes (ISO 3166-1 alpha-2, lowercase) ────────────────────────
// Used with https://flagcdn.com/w40/{code}.png — no emoji fallback needed.
// England/Scotland use subdivision codes supported by flagcdn.com.
export const TEAM_FLAGS: Record<string, string> = {
  Algeria: "dz",
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Belgium: "be",
  "Bosnia and Herzegovina": "ba",
  Brazil: "br",
  Canada: "ca",
  "Cape Verde": "cv",
  Colombia: "co",
  Croatia: "hr",
  Curacao: "cw",
  Czechia: "cz",
  "DR Congo": "cd",
  Ecuador: "ec",
  Egypt: "eg",
  England: "gb-eng",
  France: "fr",
  Germany: "de",
  Ghana: "gh",
  Haiti: "ht",
  Iran: "ir",
  Iraq: "iq",
  "Ivory Coast": "ci",
  Japan: "jp",
  Jordan: "jo",
  Mexico: "mx",
  Morocco: "ma",
  Netherlands: "nl",
  "New Zealand": "nz",
  Norway: "no",
  Panama: "pa",
  Paraguay: "py",
  Portugal: "pt",
  Qatar: "qa",
  "Saudi Arabia": "sa",
  Scotland: "gb-sct",
  Senegal: "sn",
  "South Africa": "za",
  "South Korea": "kr",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Tunisia: "tn",
  Türkiye: "tr",
  Uruguay: "uy",
  USA: "us",
  Uzbekistan: "uz",
};

// ─── Wikipedia links — shown when a team slot is revealed ────────────────────
// Each URL opens the national team's Wikipedia page (squad, history, WC wins).
export const TEAM_WIKI: Record<string, string> = {
  Algeria: "https://en.wikipedia.org/wiki/Algeria_national_football_team",
  Argentina: "https://en.wikipedia.org/wiki/Argentina_national_football_team",
  Australia: "https://en.wikipedia.org/wiki/Australia_men%27s_national_soccer_team",
  Austria: "https://en.wikipedia.org/wiki/Austria_national_football_team",
  Belgium: "https://en.wikipedia.org/wiki/Belgium_national_football_team",
  "Bosnia and Herzegovina": "https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina_national_football_team",
  Brazil: "https://en.wikipedia.org/wiki/Brazil_national_football_team",
  Canada: "https://en.wikipedia.org/wiki/Canada_men%27s_national_soccer_team",
  "Cape Verde": "https://en.wikipedia.org/wiki/Cape_Verde_national_football_team",
  Colombia: "https://en.wikipedia.org/wiki/Colombia_national_football_team",
  Croatia: "https://en.wikipedia.org/wiki/Croatia_national_football_team",
  Curacao: "https://en.wikipedia.org/wiki/Cura%C3%A7ao_national_football_team",
  Czechia: "https://en.wikipedia.org/wiki/Czech_Republic_national_football_team",
  "DR Congo": "https://en.wikipedia.org/wiki/DR_Congo_national_football_team",
  Ecuador: "https://en.wikipedia.org/wiki/Ecuador_national_football_team",
  Egypt: "https://en.wikipedia.org/wiki/Egypt_national_football_team",
  England: "https://en.wikipedia.org/wiki/England_national_football_team",
  France: "https://en.wikipedia.org/wiki/France_national_football_team",
  Germany: "https://en.wikipedia.org/wiki/Germany_national_football_team",
  Ghana: "https://en.wikipedia.org/wiki/Ghana_national_football_team",
  Haiti: "https://en.wikipedia.org/wiki/Haiti_national_football_team",
  Iran: "https://en.wikipedia.org/wiki/Iran_national_football_team",
  Iraq: "https://en.wikipedia.org/wiki/Iraq_national_football_team",
  "Ivory Coast": "https://en.wikipedia.org/wiki/Ivory_Coast_national_football_team",
  Japan: "https://en.wikipedia.org/wiki/Japan_national_football_team",
  Jordan: "https://en.wikipedia.org/wiki/Jordan_national_football_team",
  Mexico: "https://en.wikipedia.org/wiki/Mexico_national_football_team",
  Morocco: "https://en.wikipedia.org/wiki/Morocco_national_football_team",
  Netherlands: "https://en.wikipedia.org/wiki/Netherlands_national_football_team",
  "New Zealand": "https://en.wikipedia.org/wiki/New_Zealand_national_football_team",
  Norway: "https://en.wikipedia.org/wiki/Norway_national_football_team",
  Panama: "https://en.wikipedia.org/wiki/Panama_national_football_team",
  Paraguay: "https://en.wikipedia.org/wiki/Paraguay_national_football_team",
  Portugal: "https://en.wikipedia.org/wiki/Portugal_national_football_team",
  Qatar: "https://en.wikipedia.org/wiki/Qatar_national_football_team",
  "Saudi Arabia": "https://en.wikipedia.org/wiki/Saudi_Arabia_national_football_team",
  Scotland: "https://en.wikipedia.org/wiki/Scotland_national_football_team",
  Senegal: "https://en.wikipedia.org/wiki/Senegal_national_football_team",
  "South Africa": "https://en.wikipedia.org/wiki/South_Africa_national_soccer_team",
  "South Korea": "https://en.wikipedia.org/wiki/South_Korea_national_football_team",
  Spain: "https://en.wikipedia.org/wiki/Spain_national_football_team",
  Sweden: "https://en.wikipedia.org/wiki/Sweden_national_football_team",
  Switzerland: "https://en.wikipedia.org/wiki/Switzerland_national_football_team",
  Tunisia: "https://en.wikipedia.org/wiki/Tunisia_national_football_team",
  Türkiye: "https://en.wikipedia.org/wiki/Turkey_national_football_team",
  Uruguay: "https://en.wikipedia.org/wiki/Uruguay_national_football_team",
  USA: "https://en.wikipedia.org/wiki/United_States_men%27s_national_soccer_team",
  Uzbekistan: "https://en.wikipedia.org/wiki/Uzbekistan_national_football_team",
};

if (COMPANY_TEAMS.length !== MAJOR_TEAMS.length || COMPANY_TEAMS.length !== MINOR_TEAMS.length) {
  throw new Error(
    `teams.ts: All three lists must be the same length. ` +
      `Got COMPANY=${COMPANY_TEAMS.length}, MAJOR=${MAJOR_TEAMS.length}, MINOR=${MINOR_TEAMS.length}`
  );
}
